export default {
    name:'testimonials',
    title:'Testimonials',
    type: 'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string',
        },
        {
            name:'url',
            title:'Url',
            type:'url',
        },
        {
            name:'imgurl',
            title:'ImgUrl',
            type:'image',
            options:{
                hotspot:true,
            }
        },
        {
            name:'feedback',
            title:'Feedback',
            type:'string',
        }
    ]
}